import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import React from 'react';
import NavigationMenu from '@/components/NavigationMenu';
import {cn} from '@/lib/utils';
import {Toaster} from '@/components/ui/sonner';

const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	                                   children,
                                   }: Readonly<{
	children: React.ReactNode;
}>) {
	const layoutClasses = cn(
		[
			"flex",
			"flex-col",
			"items-center",
			"p-4",
			"w-full",
			"md:w-5/6",
			"lg:w-4/5",
			"xl:w-3/4",
			"2xl:w-2/3",
		],
	)
	return (
		<html lang="en">
		<body
			className={`${montserrat.variable} antialiased`}
		>
		<NavigationMenu className={"mb-4"}/>
		<main className={cn("flex", "justify-center", "w-full")}>
			<div className={layoutClasses}>
				{children}
			</div>
		</main>
		<Toaster position={"top-center"}/>
		</body>
		</html>
	);
}
